---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Networking:
  - Router:
    - abbr: TP
      href: "http://{{HOMEPAGE_VAR_ROUTER_ADDRESS}}"
  - Modem:
    - abbr: AT
      href: "http://{{HOMEPAGE_VAR_MODEM_ADDRESS}}"

- Source Code: 
  - Portfolio:
    - abbr: GH
      href: https://github.com/papatenko/portfolio
  - Odin Projects:
    - abbr: GH
      href: https://github.com/papatenko/my-odin-projects
  - Homelab:
    - abbr: GH
      href: https://github.com/papatenko/homelab
  
