---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Utilities:
    - Pihole:
        icon: pi-hole
        href: https://{{HOMEPAGE_VAR_HOST_ADDRESS}}:8443/admin
        widget:
          type: pihole
          url: https://{{HOMEPAGE_VAR_HOST_ADDRESS}}:8443
          version: 6
          key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}" # Only works as string
    - NginxProxyManager:
        icon: nginx-proxy-manager
        href: http://{{HOMEPAGE_VAR_HOST_ADDRESS}}:81
        widget:
          type: npm
          url: http://{{HOMEPAGE_VAR_HOST_ADDRESS}}:81
          username: "{{HOMEPAGE_VAR_NPM_USERNAME}}"
          password: "{{HOMEPAGE_VAR_NPM_PASSWORD}}"
    - Wireguard:
        icon: wireguard
        href: "{{HOMEPAGE_VAR_WG_URL}}"
        widget:
          type: wgeasy
          url: http://{{HOMEPAGE_VAR_HOST_ADDRESS}}:51821
          version: 2 # optional, default is 1
          username: "{{HOMEPAGE_VAR_WG_USERNAME}}"
          password: "{{HOMEPAGE_VAR_WG_PASSWORD}}"
          threshold: 2 # optional
    - Open WebUI:
        icon: open-webui
        href: "{{HOMEPAGE_VAR_AI_URL}}"

- Files:
    - Nextcloud Admin:
        icon: nextcloud
        href: https://{{HOMEPAGE_VAR_SECOND_ADDRESS}}:8080
    - Nextcloud:
        icon: nextcloud
        href: "{{HOMEPAGE_VAR_NC_URL}}"
        widget:
          type: nextcloud
          url: http://{{HOMEPAGE_VAR_SECOND_ADDRESS}}:11000
          username: "{{HOMEPAGE_VAR_NC_USERNAME}}"
          password: "{{HOMEPAGE_VAR_NC_PASSWORD}}"
    - Immich:
        icon: immich
        href: "{{HOMEPAGE_VAR_IM_URL}}"
        widget:
          type: immich
          url: http://{{HOMEPAGE_VAR_SECOND_ADDRESS}}:2283
          key: "{{HOMEPAGE_VAR_IM_API_KEY}}"
          version: 2

- Media:
    - qBittorrent:
        icon: qbittorrent
        href: http://{{HOMEPAGE_VAR_HOST_ADDRESS}}:8080
        widget:
          type: qbittorrent
          url: http://{{HOMEPAGE_VAR_HOST_ADDRESS}}:8080
          username: "{{HOMEPAGE_VAR_QB_USERNAME}}"
          password: "{{HOMEPAGE_VAR_QB_PASSWORD}}"
          enableLeechProgress: true # optional, defaults to false
          enableLeechSize: true # optional, defaults to false
    - Jellyfin:
        icon: jellyfin
        href: "{{HOMEPAGE_VAR_JF_URL}}"
        widget:
          type: jellyfin
          url: http://{{HOMEPAGE_VAR_HOST_ADDRESS}}:8096
          key: "{{HOMEPAGE_VAR_JF_API_KEY}}"
          enableBlocks: true # optional, defaults to false
          enableNowPlaying: true # optional, defaults to true
          enableUser: true # optional, defaults to false enableMediaControl: false # optional, defaults to true
          showEpisodeNumber: true # optional, defaults to false
          expandOneStreamToTwoRows: false # optional, defaults to true

- Websites:
    - Portfolio:
        icon: http://{{HOMEPAGE_VAR_SECOND_ADDRESS}}:4000/favicon.ico
        href: "{{HOMEPAGE_VAR_PORT_URL}}"
