---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

statusStyle: "dot"

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

# background:
#   image: /images/background.png
#   blur: md
