---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: 
      - /
      - /mnt/hd1

- datetime:
    text_size: xl
    format:
      timeStyle: short

