---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

layout:
  Utilities:
    style: row
    columns: 3
  Media:
    style: row
    columns: 2
  Miscellaneous:
    style: row
    columns: 3

statusStyle: dot

background:
  image: /images/background.png
  blur: md
